### ISSUE TITLE
YaWeatherAPIError 403 Forbidden

### ISSUE THREAD

**Issue by mat90c** [uburuntu/yaweather#3]
Installed last version, registered and get my api key on yandex
But when I try the example I got this error: 

raise YaWeatherAPIError(f'[{response.status_code}] {response.reason}')
yaweather.api.YaWeatherAPIError: [403] Forbidden

**Comment by uburuntu** [comment]
@mat90c hello!

With free access you should use `informers` request -- it's more simple data for non-paid subscriptions.

For example:
```python3
from yaweather import UnitedKingdom, YaWeather

y = YaWeather(api_key='secret')
res = y.informers(UnitedKingdom.London)
```

> https://yandex.com/dev/weather/doc/dg/concepts/forecast-info.html

**Comment by mat90c** [comment]
Ok, thank you
